config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  # resources :game1, only: [:index]
  
  get "/game1" => "game1#index"
  get "/game1/play/:level" => "game1#play", as: 'game1_play'
  get "/game1/instruction" => "game1#instruction"


 
  get "/pages/*page" => "pages#show"
  get "/pages/about" => "pages#about"
  get "/pages/achievement" => "pages#achievement"

  
  root "pages#show", page: "home"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/game1lv.rb
class Game1lv < ActiveRecord::Base
	# belongs_to :user
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	 # has_one :game1lv
end

app/models/userlevel.rb
class Userlevel < ActiveRecord::Base
end

app/models/userruby.rb
class Userruby < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/game1_controller.rb
class Game1Controller < ApplicationController
	
	def index
	end
	
	def play
		@game1 = Game1lv.find(params[:level])
		
		#@game1l = Game1lv.where(:level => @game1.level).limit(1).pluck(:imagelink)
		#@game1a = Game1lv.where(:level => @game1.level).limit(1).pluck(:answer)
		#@game1link = @game1l[0].to_s
		#@game1answer = @game1a[0].to_s
		
		@game1link = @game1.imagelink
		@game1answer = @game1.answer

		@hint = @game1answer[0, @game1answer.length / 2]
		
		@game1au = params["answer"]
		@game1answer_user = @game1au.to_s.downcase
		
		@game1.level = params[:level]
		
		@user = User.find(current_user)
		#@user.lvgame1 = 1
		#@user.save!
	
		if (@game1answer_user == @game1answer)
			# @game1.update({level: @game1.level + 1})
			@user.update({lvgame1: @user.lvgame1 + 1})
			@user.update({rubynumber: @user.rubynumber + 10})
			
			redirect_to game1_play_path(@game1.level + 1)
		elsif @game1answer_user != nil
		# 	flash.now[:error] = 'You are wrong! Try again'
		
		end
	end
	
	def instruction
	end

end	
  

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end
  
  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		render template: "pages/#{params[:page]}"
	end
	
	def about
	end

	def achievement
		@x = 1
		@user = User.find(current_user)
		#@userrubynumber = @user.name
	end

	 # def create
  #   	@user = User.create!(params[:user])
  #   end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
def create
	session[:current_user_email] = @useremail
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def randomized_background_image
  images = ["assets/background_0.jpg", "assets/background_1.jpg", "assets/background_1.jpg", "assets/super_random"]
  images[rand(images.size)]
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/game1_helper.rb
module Game1Helper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/game1/index.html.erb
<!DOCTYPE html>
<html>
<title> Catch The Phrase </title>

<div id="post_show">
  <h1>Catch The Phrase</h1>
  <br><br><br>
  <div class="clearfix">
    
    <div class="post_image_description">
      <%= image_tag 'catch.jpg' %>
	  <br><br><br>
      <div class="description">
        <%= simple_format "You certainly no stranger to TV game 'Chasing Pictures Getting word' right? It is interesting to discover for themselves the unique meaning of stories, humor, fun, surprise ... of the words hidden behind the familiar image. You can not stop laughing when opened the answers, the images seemed irrelevant, but when coupled together to form the interesting words. Also attending the game Catching Phrase to the laughter, plus you do not forget to save the location for acchievement!" %>
      </div>
    </div>
    <div class="post_data">
	  <br>
      <%= link_to "Play Game", game1_play_path(:level => current_user.lvgame1), class: "button" %>
      <%= link_to "Instructions", game1_instruction_path, class: "button" %>
      
    </div>

  </div>
</div>
</html>

app/views/game1/instruction.html.erb
<!DOCTYPE html>
<html>
<title> Catch The Phrase </title>

<div id="post_show">
  <h1>Instruction</h1>
  <br><br><br>
  <div class="clearfix">
    
    <div class="post_image_description">
      <%= image_tag 'catch.jpg' %>
	  <br><br><br>
      <div class="description">
        <%= simple_format "Entering the game, player has to answer the questions when watching the pictures. The attraction of the game is that the player should closely follow the suggestion in the pictures to get the answer. Then, just fill the answer in the blank. When you get the right answer, you win!" %>
      </div>
    </div>
    <div class="post_data">
	  <br>
	  <%= link_to "Play Game", game1_play_path(:level => current_user.lvgame1), class: "button" %>
      <%= link_to "Instructions", game1_instruction_path, class: "button" %>
      
    </div>

  </div>
</div>
</html>

app/views/game1/play.html.erb
<!DOCTYPE html>
<html>

<title>Welcome</title>

<div class="post">
<h1>
    <div class="pull-left">
    	Level: <%= @game1.level.inspect %>
    </div>    
    <div class="pull-right">
    	User Ruby: <%= @user.rubynumber.inspect %>
    </div>
    <center>
	<br>
	<%=image_tag @game1link, :size =>"360x360", :class => "game_image" %>
</center></h1>
</div>

<body>
	<center>
	<%= form_tag game1_play_path(@game1), :method => :get, :id => "text_form" do %>

		<%= text_field_tag "answer", "" ,class: 'textbox_game', id: 'ans', placeholder: 'Answer' %>
		<br><br>

		<button onclick="check()" class="btn blue">Submit</button>
		<button	class="btn green" onclick="hint()">Hint</button>

	<% end %>
	
	<script>

	function check(){
		var answer = '<%= @game1answer %>';
		var answer_user = document.getElementById("ans").value;
		
		if (answer_user != "") {
			if (answer_user != answer) {
				window.alert("Incorrect!");
			} else {
				window.alert("Correct! The answer is: " + answer);
			}
		}
	}
	
	function hint() {
		var str = '<%= @hint %>';
		var ruby_number = '<%= @user.rubynumber %>';

		if (ruby_number < 40) {
			window.alert("Sorry ! You don't have enough ruby to get a hint");
		} else {
			window.alert("Hint: " + str + "...");
		}
	}
	
	</script>

	
</center></body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TELEGAME</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "TELEGAME", root_path %></div>
        <nav id="collapse_navbar-collapse_navbar-ex1-collapse">
        	<% if user_signed_in? -%>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to 'Achievement', pages_achievement_path %></li>
					<li><%= link_to 'About', pages_about_path %></li>
					<li><%= link_to 'Account', edit_user_registration_path %></li>
					<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
				</ul>
			<% else -%>
				<ul class="nav navbar-nav pull-right">
					<li><%= link_to 'About', pages_about_path %></li>
					<li><%= link_to 'Sign in', new_user_session_path %></li>
					<li><%= link_to 'Sign up', new_user_registration_path %></li>
				</ul>
			<% end -%>
        </nav>
      </div>
    </div>
    </header>

	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>


</body>

<div id="footer">
<p1><center> Powered By Rails
			<br> Copyright © ICT BI5 - Group 4
</center></p1>
</div>

</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
  
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2 align = 'center'>
      <%= link_to link.title, link %><br>
     
    </h2>

  </div>
<% end %>

app/views/links/new.html.erb
<h1>Add New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="page-header">
  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br> </h1>
</div>

<div class="btn-group">
	<%= link_to 'PLAY', @link.url, class: "btn btn-primary" %>
</div>

<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>


app/views/pages/about.html.erb
<!-- This is about our web application of famous gameshows on TV. Let's play with us! -->

<!DOCTYPE html>
<html>
<title> TELEGAME </title>

<div id="post_show">
  <h1>ABOUT</h1>
  <br><br><br>
  <div class="clearfix">
    
    <div class="about_image">
      <%= image_tag 'poster_6034.jpg' %>
	  <br><br><br>
      <div class="about">
        <%= simple_format "♚ICTGroup4 consists of 5 members:
          * Ngo Sy Tung Lam
          * Ngoc An
          * Le Quoc Dat
          * Duong Hoang Linh
          * Do Dang Ngoc Kha
        All of us are studying ICT at USTH.

			♚TELEGAME is our project about Development Project Tools & Practices. We have developed a web game in order to show. Thanks for watching !" %>
      </div>
    </div>
    

  </div>
</div>
</html>

app/views/pages/achievement.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Achievement</title>
</head>
<h1><center> Achievement 
	<br><br> Level: <%= current_user.lvgame1.inspect %> <br>
	Ruby: <%= current_user.rubynumber.inspect %> </center></h1>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <p id="intro">
    Hello
    <%= current_user.name %>
    <br/>

    <span>
     Join us to get more gift!
    </span>
  </p>
<% else %>
  <p id="intro">
    Welcome to our Website
    <br/>
    <span>
      Sign In now to play our Free Games!
    </span>
  </p>
<% end %>


<% if user_signed_in? -%>

	<br>
	<div id="posts"><center>
		<div class="post"><center>
		   <%= link_to image_tag("phrase.jpg", :class => "post_image"), game1_path %>
		   
		  <div class="post_content">
			<div class="title">
			  <h2>
				<%= link_to "Catch The Phrase", game1_path %>
			  </h2>
			</div>
			<div class="data clearfix">
			  <p>
				The famous word guessing game is now available on our website. Try now for FREE!
			  </p>
			</div>
		  </div>
		</div>  
	</div>
	
	
	
	
<% else -%>
	<br>
	<div id="posts"><center>
		<div class="post"><center>
		   <%= link_to image_tag("phrase.jpg", :class => "post_image"), new_user_session_path %>
		   
		  <div class="post_content">
			<div class="title">
			  <h2>
				<%= link_to "Catch The Phrase", new_user_session_path %>
			  </h2>
			</div>
			<div class="data clearfix">
			  <p>
				The famous word guessing game is now available on our website. Try now for FREE!
			  </p>
			</div>
		  </div>
		</div>  
	</div>
	

<% end -%>